lucky_numbers = [4,6,9,15,25,12,67,1,3,55]
friends = ["John", "Kevin", "Joe", "Tom", "Jerry"]
# friends.extend(lucky_numbers)
friends.append("Alice")
friends.insert(1,"Kelly")
friends.remove("Joe")
friends.pop()
print(friends)
print(friends.index("Kelly"))
print(friends.count("Tom"))
friends.sort()
print(friends)
lucky_numbers.sort()
lucky_numbers.reverse()
print(lucky_numbers)
friends2 = friends.copy()
print(friends2)
# friends.clear()
# print(friends)